aruha-330: 95, 98, 99 percentiles
zalando/nakadi-end2end pull request #6
Opened 2016-09-29 11:39 UTC by adyach

2016-09-29 12:57 UTC, rcillo commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
Why 95.99 and then -1?

2016-09-29 13:02 UTC, adyach commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
@rcillo I believe python arrays start from index 0. For example we take array of 10 elements and want to calculate 90% percentile then according to formula we get:
`(10 * 90 / 100) - 1 = 8` which is 9th element of the array. does it look right?

2016-09-29 13:05 UTC, rcillo commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
The `-1` part is clear now, it's about adjusting for zero indexed array. But the `**.99` still doesn't , since this example users a round `90`.

2016-09-29 13:06 UTC, adyach commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
Maybe -1 it has to be proportional to the size of the array.

2016-09-29 13:31 UTC, rcillo commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
Maybe having some tests to check examples of input/output would help to understand what it does.

2016-10-11 07:56 UTC, antban requested changes
Reviewed

2016-10-11 07:56 UTC, antban commented on end2end/connectors/nakadi.py
> +        'owning_application': 'stups_aruha-test-end2end-nakadi',
I think that this should be kept in configuration

2016-10-11 07:56 UTC, antban commented on setup.py
> +    setup_package()
Das ist nicht stakenbochen!
If we are adding setup.py, we should add requirements.txt or something like that. With tornado and reqeusts libraries...

2016-10-11 07:56 UTC, antban commented on end2end/metric.py
> +        self.sample_size = os.getenv('PERCENTILE_SAMPLE_SIZE', 1000)
It is better to pass this value as parameter here, and get from env in Meter.

2016-10-11 08:13 UTC, adyach commented on end2end/metric.py
> +        self.sample_size = os.getenv('PERCENTILE_SAMPLE_SIZE', 1000)
@antban 8d93962

2016-10-11 08:13 UTC, adyach commented on end2end/connectors/nakadi.py
> +        'owning_application': 'stups_aruha-test-end2end-nakadi',
@antban 560dcb1

2016-10-11 08:13 UTC, adyach commented on setup.py
> +    setup_package()
@antban 560dcb1

2016-10-11 08:37 UTC, adyach commented on end2end/metric.py
> +            self.p95 = sorted_sample[int(math.ceil((size * 95.99) / 100)) - 1]
@rcillo added test

2016-10-11 08:56 UTC, rcillo commented
:shipit:

2016-10-11 09:00 UTC, antban approved these changes
:+1:

2016-10-11 09:01 UTC, merged